# ----------------------------------------
# Base URL or website root directory to check relative URLs.
base = "https://practical.li/clojure/"

# Only test links with the given schemes (e.g. https).
# Omit to check links with any other scheme.
# At the moment, we support http, https, file, and mailto.
scheme = ["https"]

# https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox
# user_agent = ["curl/8.4.0"]
user_agent = "Mozilla/5.0 (X11; Linux x86_64; rv:153.0) Gecko/20100101 Firefox/153.0"

# ----------------------------------------
# Exclusions

# Exclude URLs and mail addresses from checking (supports regex).
exclude = ['^https://127.0.0.0', '^https://www\.linkedin\.com', '^https://web\.archive\.org/web/']

# Exclude these filesystem paths from getting checked.
exclude_path = ["mkdocs.yml", "overrides", "includes", ".github", ".git"]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = true

# Check mail addresses
include_mail = false
# ----------------------------------------
